apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: alloy-self-monitoring
  namespace: alloy
  labels:
    app.kubernetes.io/name: alloy-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy-metrics
  podMetricsEndpoints:
  - port: http-metrics
    path: /metrics
    interval: 60s
