apiVersion: v1
kind: Service
metadata:
  name: alloy-gateway-otlp
  namespace: alloy
spec:
  ports:
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: http-otlp
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: alloy
