# OpenTelemetry Demo prod overrides
opentelemetry-demo:
  opentelemetry-collector:
    enabled: false
  jaeger:
    enabled: false
  opensearch:
    enabled: false
  grafana:
    enabled: false
  components:
    kafka:
      enabled: false
    llm:
      enabled: false
    load-generator:
      enabled: false
