{{- if .Values.grafanaOperatorCRs.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Values.grafanaOperatorCRs.instance.name }}
  labels:
{{- toYaml .Values.grafanaOperatorCRs.instance.labels | nindent 4 }}
spec:
  external:
{{- toYaml .Values.grafanaOperatorCRs.instance.external | nindent 4 }}
{{- end }}
