{{- $grafanaOperatorCRs := .Values.grafanaOperatorCRs | default dict }}
{{- if ($grafanaOperatorCRs.enabled | default false) }}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ $grafanaOperatorCRs.instance.name }}
  labels:
{{- toYaml $grafanaOperatorCRs.instance.labels | nindent 4 }}
spec:
  external:
{{- toYaml $grafanaOperatorCRs.instance.external | nindent 4 }}
{{- end }}
