# Stage int: Freight nur nach Verifikation in dev; Promotion aktualisiert Values + Chart
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: int
  namespace: kargo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: bwcloud-warehouse
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/saadisfy/bwcloud-gitops.git
        - name: targetBranch
          value: main
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: ${{ vars.targetBranch }}
                path: ./out
        - uses: yaml-update
          as: update-values
          config:
            path: ./out/apps/spring-petclinic/int/values.yaml
            updates:
              - key: image.tag
                value: ${{ imageFrom("ghcr.io/saadisfy/spring-petclinic").Tag }}
        - uses: git-commit
          config:
            path: ./out
            message: |
              ${{ ctx.stage }}: ${{ outputs["update-values"].commitMessage }}
        - uses: git-push
          config:
            path: ./out
            targetBranch: ${{ vars.targetBranch }}
