{{- if .Values.otelCollector.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Values.otelCollector.name | default "otel-collector" }}
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      otlp:
        endpoint: mimir-distributor.{{ .Values.mimirNamespace | default "mimir" }}.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          exporters: [otlp]
{{- end }}
