apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https-argocd
    hostname: argocd.saadisfy.me
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: main-gateway-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: https-grafana
    hostname: grafana.saadisfy.me
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: grafana-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: https-kargo
    hostname: kargo.saadisfy.me
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: kargo-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: https-mimir
    hostname: mimir.saadisfy.me
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: mimir-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: https-mimir-query
    hostname: mimir-query.saadisfy.me
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: mimir-query-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: https-otel
    hostname: opentelemetry-demo.saadisfy.me
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: main-gateway-tls
    allowedRoutes:
      namespaces:
        from: All
  - name: https-petclinic
    hostname: spring-petclinic.saadisfy.me
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: main-gateway-tls
    allowedRoutes:
      namespaces:
        from: All
