apiVersion: v2
name: mimir-wrapper
description: Wrapper for Grafana Mimir distributed Helm chart (low resources)
version: 0.1.0
dependencies:
  - name: mimir-distributed
    version: "6.3.0"
    repository: https://grafana.github.io/helm-charts
