# Grafana int stage overrides
grafana:
  nameOverride: grafana-int
  fullnameOverride: grafana-int
  adminPassword: "REPLACE_GRAFANA_ADMIN_PASSWORD"
  ingress:
    hosts:
      - grafana-int.saadisfy.me
    tls:
      - secretName: grafana-int-tls
        hosts:
          - grafana-int.saadisfy.me
