# Grafana dev stage overrides
grafana:
  nameOverride: grafana
  fullnameOverride: grafana
  ingress:
    hosts:
      - grafana.saadisfy.me
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.saadisfy.me
