# OpenTelemetry Demo - base values
# Full demo stack enabled (chart defaults).
opentelemetry-demo:
  components:
    frontend-proxy:
      podAnnotations:
        reloader.stakater.com/auto: "true"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - host: opentelemetry-demo.saadisfy.me
            paths:
              - path: /
                pathType: Prefix
                port: 8080
