# Azure OBS stage overrides
mimir-distributed:
  distributor:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 200m
        memory: 1Gi
  gateway:
    ingress:
      hosts:
        - host: az-mimir.saadisfy.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: mimir-tls
          hosts:
            - az-mimir.saadisfy.me
  ingester:
    resources:
      requests:
        cpu: 200m
        memory: 1536Mi
      limits:
        cpu: 200m
        memory: 1536Mi
    zoneAwareReplication:
      enabled: true

queryFrontendIngress:
  host: az-mimir-query.saadisfy.me
