apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alloy
  namespace: argocd
spec:
  # Nur prod deployed
  generators:
    - list:
        elements:
          - stage: noctua
            namespace: alloy
  template:
    metadata:
      name: alloy
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: 'apps/alloy/{{stage}}'
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
