apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - stage: noctua
            namespace: minio
  template:
    metadata:
      name: minio
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: 'apps/minio/{{stage}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
