apiVersion: v2
name: otel-operator-wrapper
description: Wrapper for OpenTelemetry Operator Helm chart
version: 0.1.0
dependencies:
  - name: opentelemetry-operator
    version: "0.49.0"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
