# Grafana dev stage overrides
grafana:
  nameOverride: grafana-dev
  fullnameOverride: grafana-dev
  ingress:
    hosts:
      - grafana-dev.saadisfy.me
    tls:
      - secretName: grafana-dev-tls
        hosts:
          - grafana-dev.saadisfy.me
