apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy-wrapper
data:
{{- $files := list
  "config.alloy"
  "destinations.alloy"
  "common_processing.alloy"
  "application_pipeline.alloy"
  "pod_logs_pipeline.alloy"
  "metrics_pipeline.alloy"
  "alloy_scrape.alloy"
  "annotation_autodiscovery_scrape.alloy"
  "kubelet_scrape.alloy"
  "kubelet_resources_scrape.alloy"
  "cadvisor_scrape.alloy"
  "ksm_scrape.alloy"
  "kube_dns_scrape.alloy"
  "controllermanager_scrape.alloy"
  "scheduler_scrape.alloy"
  "kubeproxy_scrape.alloy"
  "apiserver_scrape.alloy"
  "node_exporter_scrape.alloy"
}}
{{- range $file := $files }}
  {{ $file }}: |-
{{ tpl ($.Files.Get (printf "files/alloy/%s" $file)) $ | nindent 4 }}
{{- end }}
