minio:
  image: "minio/minio"
  tag: "latest"
  credentialsSecret:
    name: minio-credentials
    rootUserKey: MINIO_ROOT_USER
    rootPasswordKey: MINIO_ROOT_PASSWORD
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"
  persistence:
    size: "10Gi"
    storageClass: "local-path"

mc:
  image: "minio/mc"
  tag: "latest"
