minio:
  image: "minio/minio"
  tag: "latest"
  rootUser: "minioadmin"
  rootPassword: "REPLACE_ROOT_PASSWORD"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"
  persistence:
    size: "10Gi"
    storageClass: "local-path"

mc:
  image: "minio/mc"
  tag: "latest"
