elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  antiAffinity: "soft"
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
      xpack.security.http.ssl.enabled: false
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  volumeClaimTemplate:
    resources:
      requests:
        storage: 2Gi

kibana:
  elasticsearchHosts: "http://elasticsearch-master:9200"
  elasticsearchCertificateSecret: ""
  elasticsearchCredentialSecret: ""
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
