apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-mimir
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: ghcr.io/loafoe/provider-mimir:v0.9.0
---
apiVersion: mimir.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: mimir-creds
      key: credentials
