# Azure OBS ApplicationSets
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: argocd
  template:
    metadata:
      name: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/argocd/prod
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
            - ../azure-obs/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: argocd-secret
          namespace: argocd
          jsonPointers:
            - /data/admin.password
            - /data/admin.passwordMtime
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-priority
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cluster-priority
            namespace: kube-system
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/cluster-priority/prod
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reloader
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: reloader
  template:
    metadata:
      name: reloader
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/reloader/prod
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: istio-system
  template:
    metadata:
      name: istio
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/istio/prod
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istio-validator-istio-system
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
            - .webhooks[]?.failurePolicy
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
            - .webhooks[]?.failurePolicy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mimir
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: mimir
  template:
    metadata:
      name: mimir
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/mimir/prod
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
            - ../azure-obs/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alloy
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: alloy
  template:
    metadata:
      name: alloy
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/alloy/prod
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: grafana
  template:
    metadata:
      name: grafana
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/grafana/prod
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
            - ../azure-obs/values.yaml
          skipCrds: false
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-operator
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: otel-operator
  template:
    metadata:
      name: otel-operator
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/otel-operator/prod
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: opentelemetry-demo
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: opentelemetry-demo
  template:
    metadata:
      name: opentelemetry-demo
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/opentelemetry-demo/prod
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
            - ../azure-obs/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: kargo
  template:
    metadata:
      name: kargo
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/kargo/prod
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
            - ../azure-obs/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: kargo-api
          namespace: kargo
          jsonPointers:
            - /data/ADMIN_ACCOUNT_PASSWORD_HASH
            - /data/ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-projects
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: kargo-projects
            namespace: kargo-projects
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/kargo-projects
        directory:
          recurse: true
          exclude: '{**/*stage-dev.yaml,**/*stage-int.yaml}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
