apiVersion: v2
name: reloader-wrapper
description: Wrapper for Stakater Reloader Helm chart
version: 0.1.0
dependencies:
  - name: reloader
    version: "1.4.12"
    repository: https://stakater.github.io/stakater-charts
