apiVersion: v2
name: alloy-wrapper
description: Wrapper for Alloy, kube-state-metrics and node-exporter
version: 0.1.0
dependencies:
  - name: alloy
    version: "1.5.2"
    repository: https://grafana.github.io/helm-charts
  - name: kube-state-metrics
    version: "7.1.0"
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-node-exporter
    version: "4.51.0"
    repository: https://prometheus-community.github.io/helm-charts
