apiVersion: v2
name: kibana
description: Helm chart for Kibana using official subchart
type: application
version: 0.1.0
dependencies:
  - name: kibana
    version: "8.5.1"
    repository: https://helm.elastic.co
