kibana:
  # Point to the official ES master service
  elasticsearchHosts: "https://elasticsearch-master:9200"

  # Use the cert and credentials secrets created by the elasticsearch chart
  elasticsearchCertificateSecret: elasticsearch-master-certs
  elasticsearchCertificateAuthoritiesFile: ca.crt
  elasticsearchCredentialSecret: elasticsearch-master-credentials

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
