apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: grafana-warehouse
  namespace: grafana
spec:
  freightCreationPolicy: Automatic
  subscriptions:
    # Watch git repo for changes in apps/grafana/prod
    - git:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        branch: main
        includePaths:
          - apps/grafana/prod/Chart.yaml
          - apps/grafana/prod/values.yaml
          - apps/grafana/prod/templates/**
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 20
