# Tempo az-obs values
# Keep empty to use upstream chart defaults.
tempo-distributed:
  traces:
    otlp:
      grpc:
        enabled: true
  metricsGenerator:
    enabled: true
  overrides:
    defaults:
      metrics_generator:
        processors:
          - local-blocks
