apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  # Nur prod deployed
  generators:
    - list:
        elements:
          - stage: prod
            name: grafana
            namespace: grafana
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: 'apps/grafana/{{stage}}'
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
          skipCrds: false
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
