apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-crs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - stage: prod
            namespace: kargo
  template:
    metadata:
      name: kargo-crs
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: apps/kargo/crs
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
