apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-operator
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - stage: dev
            namespace: otel-operator-dev
          - stage: int
            namespace: otel-operator-int
          - stage: prod
            namespace: otel-operator
  template:
    metadata:
      name: 'otel-operator-{{stage}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        targetRevision: main
        path: 'apps/otel-operator/{{stage}}'
        helm:
          valueFiles:
            - ../base/values.yaml
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
