apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: grafana-warehouse
  namespace: grafana
spec:
  freightCreationPolicy: Automatic
  subscriptions:
    # Watch git repo for changes in apps/grafana/dev
    - git:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        branch: main
        includePaths:
          - apps/grafana/dev/**
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 10
