apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: grafana-warehouse
  namespace: grafana
spec:
  freightCreationPolicy: WhenChartVersionChanges
  subscriptions:
    # Watches apps/grafana/dev/Chart.yaml for wrapper version changes
    - chart:
        repoURL: https://github.com/saadisfy/bwcloud-gitops.git
        name: apps/grafana/dev
        discoveryLimit: 10
